;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        hydra-mark/mc/mark-next-like-this
        ignore
        keyboard-escape-quit
        multiple-cursors-hydra/mc/edit-lines-and-exit
        multiple-cursors-hydra/mc/mark-all-like-this-and-exit
        multiple-cursors-hydra/mc/mark-next-like-this
        org-delete-char
        org-end-of-line
        org-metaright
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
