;; generated by function: `autoload:generate-loaddefs-file'.

;;;### (autoloads nil "action/editing" "action/editing.el" (0 0 0
;;;;;;  0))
;;; Generated autoloads from action/editing.el

(autoload 'move-to-char "action/editing" "\


\(fn ARG CHAR)" t)

(autoload 'mark-to-char-exclusive "action/editing" "\
Mark up to but not including ARGth occurrence of CHAR.

\(fn ARG CHAR)" t)

(autoload 'mark-to-char-inclusive "action/editing" "\
Mark up to and including ARGth occurrence of CHAR.

\(fn ARG CHAR)" t)

;;;***

;;;### (autoloads nil "action/git-clone" "action/git-clone.el" (0
;;;;;;  0 0 0))
;;; Generated autoloads from action/git-clone.el

(autoload 'git-clone-clipboard-url "action/git-clone" "\
Clone git URL in clipboard asynchronously and open in dired when finished." t)

;;;***

;;;### (autoloads nil "action/org-capture" "action/org-capture.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from action/org-capture.el

(register-definition-prefixes "action/org-capture" '("org-capture>make-frame"))

;;;***

;;;### (autoloads nil "action/buffers" "action/buffers.el" (0 0 0
;;;;;;  0))
;;; Generated autoloads from action/buffers.el

(autoload 'my>buffer-delete-file-and-buffer "action/buffers" "\
Kill the current buffer and deletes the file it is visiting." t)

(autoload 'my>buffer-rename-file-and-buffer "action/buffers" "\
Rename the current buffer and file it is visiting." t)

;;;***
